// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFP7BMXEFPLpkFUReijuGVthbkca2Mz-o',
    appId: '1:655040482753:web:9eda4857368b8687c33340',
    messagingSenderId: '655040482753',
    projectId: 'aarogyam-fa6b9',
    authDomain: 'aarogyam-fa6b9.firebaseapp.com',
    storageBucket: 'aarogyam-fa6b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS5B7ZZS1ma54TEkBl6TzMsFZVPfjPhRo',
    appId: '1:655040482753:android:ec03aa444ef5e566c33340',
    messagingSenderId: '655040482753',
    projectId: 'aarogyam-fa6b9',
    storageBucket: 'aarogyam-fa6b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpiLOWXhXje2KNmAwFXkV9YU7QN6ObrYQ',
    appId: '1:655040482753:ios:d7f09d294a39415bc33340',
    messagingSenderId: '655040482753',
    projectId: 'aarogyam-fa6b9',
    storageBucket: 'aarogyam-fa6b9.firebasestorage.app',
    iosBundleId: 'com.example.aarogya',
  );
}
